### ISSUE TITLE
Up button breaks page

### ISSUE THREAD

**Issue by gminova** [crianonim/svarog#7]
when I press the UP button on the very top the whole page goes blank

**Comment by crianonim** [comment]
Hi Gigi!
Thanks for checking out my project, you were unlucky to see the broken build (should test before merging to master!). It was fixed in this commit:
https://github.com/crianonim/svarog/commit/e1d32366e1c24324078bfbe88a1e537ba34619aa
I'm grateful for your interest, keep it going!

**Comment by gminova** [comment]
:dancer:
